version: '3'
services:
  minecraft-server:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: true
      VERSION: 1.20.6
      TYPE: FABRIC
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./mods/1.20.1:/data/mods
  api:
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    ports:
      - 8000:8000
    volumes: 
      - ./api/src:/app/src
    command: 
      - uvicorn
      - src.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload
    env_file:
      - .env