version: '3'
services:
  server:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: true
      VERSION: 1.21.1
      TYPE: FABRIC
      HARDCORE: false
      MEMORY: ${MEMORY}
      DIFFICULTY: hard
    volumes:
      - ./data:/data
      - ./mods:/data/mods